build:
    nodes:
        coverage:
            tests:
                override:
                    - command: npm test-scrutinizer
                      coverage:
                          file: build/coverage/clover.xml
                          format: clover
